updated

diff --git a/.github/workflows/demo2A.yml b/.github/workflows/demo2A.yml
--- a/.github/workflows/demo2A.yml
+++ b/.github/workflows/demo2A.yml
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Step 1
-        run: echo "This is Job 1"
+        run: exit 1  # Simulate failure
 
   job2:
     needs: job1
